import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import ProgressBar from "@/components/layout/ProgressBar";

const ralewaySans = Raleway({
  subsets: ["latin"],
  weight: ["500", "700"],
});

export const metadata: Metadata = {
  title: "Foso",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ralewaySans.className} antialiased`}>
        <ProgressBar />
        <Header />
        {children}
      </body>
    </html>
  );
}
